# Generated by Django 5.0.3 on 2024-04-21 20:56

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equip', models.CharField(max_length=100, primary_key=builtins.id, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('mask', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.CharField(max_length=15)),
                ('matricula', models.CharField(blank=True, max_length=15, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('equip_id', models.CharField(blank=True, max_length=10, null=True)),
                ('equip_nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Refeicao',
            fields=[
                ('id_grup_ref', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inter_grup_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_ref', models.CharField(max_length=10)),
                ('ref', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_param', models.CharField(max_length=15)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id_ref', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('permissao', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('admissao', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_de_custo', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('credencial', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.SlugField(blank=True, null=True)),
                ('grup_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.grupo_refeicao')),
            ],
        ),
        migrations.AddField(
            model_name='grupo_refeicao',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.refeicao'),
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('credencial', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.funcionario')),
                ('grup_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.grupo_refeicao')),
            ],
        ),
    ]
