# Generated by Django 5.0.3 on 2024-08-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='mod_credito_usu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='mod_credito_visi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='mod_padrao_usu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='mod_padrao_visi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
